#!/usr/bin/env python3
"""
cc-magcal.py - Magnetometer hard/soft-iron calibration helper for Week 15.

While the firmware streams raw magnetometer samples (one "mx,my,mz" line per
sample, printed by a dedicated calibration build of the firmware), rotate the
board slowly through every orientation for ~30 seconds — the "figure-eight in
the air" dance. This tool records the cloud of points, fits the min/max box on
each axis, and emits the hard-iron offset and diagonal soft-iron scale as a C
snippet you paste into your imu_calibration_t initializer.

This is the cheap diagonal calibration described in Lecture 1 section 4: it
recenters the ellipsoid (hard iron) and equalizes the per-axis spans (diagonal
soft iron). It does NOT solve the full off-diagonal soft-iron shear; for that,
fit an ellipsoid with numpy (see the homework).

Usage:
    cc-magcal.py [--port /dev/cu.usbmodem...] [--seconds 30]

Output: prints the calibration constants and writes mag_cal.h.

Citations:
    - Lecture 1 section 4 (hard/soft iron); the min/max diagonal method.
"""

from __future__ import annotations

import argparse
import sys
import time
from typing import Optional

try:
    import serial
    import serial.tools.list_ports
except ImportError:
    sys.exit("error: pyserial is required. pip install pyserial")


def find_pico_port() -> Optional[str]:
    for port in serial.tools.list_ports.comports():
        if port.vid == 0x2E8A:
            return port.device
    return None


def collect(port: str, baud: int, seconds: float):
    ser = serial.Serial(port, baud, timeout=1.0)
    ser.reset_input_buffer()

    lo = [1e9, 1e9, 1e9]
    hi = [-1e9, -1e9, -1e9]
    n = 0
    t0 = time.time()
    print(f"cc-magcal: rotate the board through ALL orientations for "
          f"{seconds:.0f} s...")

    while time.time() - t0 < seconds:
        raw = ser.readline().decode("ascii", errors="replace").strip()
        if not raw or raw.startswith("#"):
            continue
        parts = raw.split(",")
        if len(parts) != 3:
            continue
        try:
            v = [float(p) for p in parts]
        except ValueError:
            continue
        for i in range(3):
            lo[i] = min(lo[i], v[i])
            hi[i] = max(hi[i], v[i])
        n += 1
        if n % 100 == 0:
            remaining = seconds - (time.time() - t0)
            print(f"  {n} samples, {remaining:4.1f}s left, "
                  f"span x={hi[0]-lo[0]:.1f} y={hi[1]-lo[1]:.1f} "
                  f"z={hi[2]-lo[2]:.1f} uT")

    ser.close()
    return lo, hi, n


def compute(lo, hi):
    hard = [(hi[i] + lo[i]) / 2.0 for i in range(3)]
    semi = [(hi[i] - lo[i]) / 2.0 for i in range(3)]
    avg = sum(semi) / 3.0
    soft = [avg / semi[i] if semi[i] > 1e-6 else 1.0 for i in range(3)]
    return hard, soft


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Magnetometer hard/soft-iron calibration for C7 Week 15.")
    ap.add_argument("--port", type=str, default=None)
    ap.add_argument("--baud", type=int, default=115200)
    ap.add_argument("--seconds", type=float, default=30.0)
    args = ap.parse_args()

    port = args.port or find_pico_port()
    if port is None:
        sys.exit("error: could not find a Pico CDC port.")

    lo, hi, n = collect(port, args.baud, args.seconds)
    if n < 100:
        sys.exit(f"error: only {n} samples; is the calibration firmware running?")

    hard, soft = compute(lo, hi)

    print("\ncc-magcal: results")
    print(f"  hard-iron offset (uT): {hard[0]:.2f} {hard[1]:.2f} {hard[2]:.2f}")
    print(f"  soft-iron diagonal:    {soft[0]:.4f} {soft[1]:.4f} {soft[2]:.4f}")

    header = (
        "/* Generated by cc-magcal.py. Paste into your imu_calibration_t. */\n"
        "#ifndef MAG_CAL_H_\n#define MAG_CAL_H_\n"
        f"static const float MAG_HARD_IRON[3] = "
        f"{{ {hard[0]:.4f}f, {hard[1]:.4f}f, {hard[2]:.4f}f }};\n"
        f"static const float MAG_SOFT_IRON[3] = "
        f"{{ {soft[0]:.4f}f, {soft[1]:.4f}f, {soft[2]:.4f}f }};\n"
        "#endif /* MAG_CAL_H_ */\n"
    )
    with open("mag_cal.h", "w") as f:
        f.write(header)
    print("cc-magcal: wrote mag_cal.h")


if __name__ == "__main__":
    main()
